import type { Metadata } from "next";
import { Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import "./embla.css";
import Header from "@/components/Header";

const montserrat = Montserrat_Alternates({
	subsets: ["latin-ext"],
	weight: ["100", "400",]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={montserrat.className}>
				<Header />
				{children}</body>
		</html>
	);
}
