/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0D7RdqHmSfk
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
	subsets: ['latin'],
	display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import Logo from "../Logo"
import MenuItems from "../MenuItems"
import { JSX, SVGProps } from "react"

export function Header() {
	return (
		<header className="sticky bg-white top-0 z-50 flex items-center justify-between px-4 py-3 bg-background border-b">
			<Link href="/" className="flex items-center gap-2" prefetch={false}>
				<Logo />

			</Link>
			<div className="flex items-center gap-2 md:ml-auto">
				<Button variant="ghost" size="icon" className="rounded-full md:hidden">
					<MenuIcon className="h-6 w-6" />
					<span className="sr-only">Toggle menu</span>
				</Button>
				<nav className="hidden md:flex items-center gap-6">
					<MenuItems />
				</nav>
				<Button><Link href={'/adquira'} >Adquira</Link></Button>
			</div>
		</header>
	)
}

function MenuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<line x1="4" x2="20" y1="12" y2="12" />
			<line x1="4" x2="20" y1="6" y2="6" />
			<line x1="4" x2="20" y1="18" y2="18" />
		</svg>
	)
}